# Generated by Django 3.1.1 on 2021-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='git_user',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
