# Generated by Django 3.2.4 on 2021-06-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_git_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='git_user',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
