# Generated by Django 3.2.4 on 2021-06-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_git_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git_user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
