# Generated by Django 3.2.4 on 2021-06-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20210616_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('isuue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('issue_details', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
