# Generated by Django 3.2.4 on 2021-06-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_rename_isuue_id_contact_issue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
